<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitb17d4e23c22504c9d93c7cfdb6e6aae7
{
    public static $prefixLengthsPsr4 = array (
        'c' => 
        array (
            'chriskacerguis\\RestServer\\' => 26,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'chriskacerguis\\RestServer\\' => 
        array (
            0 => __DIR__ . '/..' . '/chriskacerguis/codeigniter-restserver/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitb17d4e23c22504c9d93c7cfdb6e6aae7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitb17d4e23c22504c9d93c7cfdb6e6aae7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
